# Generated by Django 2.1 on 2018-10-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.CharField(max_length=100)),
                ('Quota', models.CharField(max_length=100)),
                ('Cut_off', models.CharField(max_length=100)),
                ('Seat_reservation', models.CharField(max_length=100)),
                ('Admisson_process', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Current_designation', models.CharField(max_length=100)),
                ('Comapany', models.CharField(max_length=100)),
                ('Sort_order', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvals', models.CharField(max_length=100)),
                ('other_approval', models.CharField(max_length=100)),
                ('Accreditations', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_entity', models.CharField(max_length=100)),
                ('Entity_name', models.CharField(max_length=100)),
                ('College_website', models.URLField(max_length=100)),
                ('Contactno', models.PositiveIntegerField()),
                ('Contactno2', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('campus_size', models.PositiveIntegerField()),
                ('total_faculty', models.PositiveIntegerField()),
            ],
        ),
    ]
