# Generated by Django 2.1 on 2018-10-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181017_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='college_admission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.CollegeDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvals',
            name='college_approval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.CollegeDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilites',
            name='college_facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.CollegeDetails'),
            preserve_default=False,
        ),
    ]
